apiVersion: v1
kind: Pod
metadata:
  labels:
    app: app-pod
    #Owner: Dhruv
  name: app-pod
spec:
  containers:
  - image: 269793566624.dkr.ecr.us-east-1.amazonaws.com/apprepo:latest
    name: app-pod
    env:
      - name: DBHOST
        value: "10.244.0.5"   
      - name: DBPORT
        value: "3306" 
      - name: DBUSER
        value: "root"
      - name: DATABASE
        value: "employees"
      - name: DBPWD
        value: "123"
      - name: APP_COLOR
        value: "blue"
    ports:
      - containerPort: 8080
        name: app-pod  
  dnsPolicy: ClusterFirst
  restartPolicy: Always
