apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-pod
  labels:
    app: app-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-pod
  template:
    metadata:
      labels:
        app: app-pod
    spec:
      containers:
      - image: 269793566624.dkr.ecr.us-east-1.amazonaws.com/apprepo:latest
        name: app-pod
        env:
          - name: DBHOST
            value: "10.244.0.5"
          - name: DBPORT
            value: "3306"
          - name: DBUSER
            value: "root"
          - name: DATABASE
            value: "employees"
          - name: DBPWD
            value: "123"
          - name: APP_COLOR
            value: "blue"
        ports:
          - containerPort: 8080
            name: app-pod
      dnsPolicy: ClusterFirst
      restartPolicy: Always
